# coding=utf-8


class MODE:
    SORTER = "SORTER"
    DEDUP = "DEDUP"


# noinspection SpellCheckingInspection
class MIMES_TYPES:
    NODE_MODULES = "node_modules"
    IDEA = "idea_file"
    GIT = "git-file"
    AUDIO = 'audio'
    VIDEO = "video"
    DOCUMENT = "documents"
    IMAGE = "images"
    ARCHIVE = 'archives'
    OTHER = 'other'
    BOOK = "book"

    mimes_list = {"application/acad": {"extension": [".dwg"], "group": OTHER},
                  "application/arj": {"extension": [".arj"], "group": OTHER},
                  "application/base64": {"extension": [".mm", ".mme"], "group": OTHER},
                  "application/binhex": {"extension": [".hqx"], "group": OTHER},
                  "application/binhex4": {"extension": [".hqx"], "group": OTHER},
                  "application/book": {"extension": [".boo", ".book"], "group": OTHER},
                  "application/cdf": {"extension": [".cdf"], "group": OTHER},
                  "application/clariscad": {"extension": [".ccad"], "group": OTHER},
                  "application/commonground": {"extension": [".dp"], "group": OTHER},
                  "application/drafting": {"extension": [".drw"], "group": OTHER},
                  "application/dsptype": {"extension": [".tsp"], "group": OTHER},
                  "application/dxf": {"extension": [".dxf"], "group": OTHER},
                  "application/ecmascript": {"extension": [".js"], "group": OTHER},
                  "application/envoy": {"extension": [".evy"], "group": OTHER},
                  "application/excel": {"extension": [".xlw", ".xlv", ".xlt", ".xls", ".xlm", ".xll", ".xlk",
                                                      ".xld", ".xlc", ".xl", ".xla", ".xlb"], "group": OTHER},
                  "application/fractals": {"extension": [".fif"], "group": OTHER},
                  "application/freeloader": {"extension": [".frl"], "group": OTHER},
                  "application/futuresplash": {"extension": [".spl"], "group": OTHER},
                  "application/gnutar": {"extension": [".tgz"], "group": OTHER},
                  "application/groupwise": {"extension": [".vew"], "group": OTHER},
                  "application/hlp": {"extension": [".hlp"], "group": OTHER},
                  "application/hta": {"extension": [".hta"], "group": OTHER},
                  "application/i-deas": {"extension": [".unv"], "group": OTHER},
                  "application/iges": {"extension": [".iges", ".igs"], "group": OTHER},
                  "application/inf": {"extension": [".inf"], "group": OTHER},
                  "application/java": {"extension": [".class"], "group": OTHER},
                  "application/java-byte-code": {"extension": [".class"], "group": OTHER},
                  "application/javascript": {"extension": [".js"], "group": OTHER},
                  "application/lha": {"extension": [".lha"], "group": OTHER},
                  "application/lzx": {"extension": [".lzx"], "group": OTHER},
                  "application/mac-binary": {"extension": [".bin"], "group": OTHER},
                  "application/mac-binhex": {"extension": [".hqx"], "group": OTHER},
                  "application/mac-binhex40": {"extension": [".hqx"], "group": OTHER},
                  "application/mac-compactpro": {"extension": [".cpt"], "group": OTHER},
                  "application/macbinary": {"extension": [".bin"], "group": OTHER},
                  "application/marc": {"extension": [".mrc"], "group": OTHER},
                  "application/mbedlet": {"extension": [".mbd"], "group": OTHER},
                  "application/mcad": {"extension": [".mcd"], "group": OTHER},
                  "application/mime": {"extension": [".aps"], "group": OTHER},
                  "application/mspowerpoint": {"extension": [".pot", ".pps", ".ppt", ".ppz"], "group": OTHER},
                  "application/msword": {"extension": [".word", ".wiz", ".w6w", ".dot", ".doc"], "group": DOCUMENT},
                  "application/mswrite": {"extension": [".wri"], "group": OTHER},
                  "application/netmc": {"extension": [".mcp"], "group": OTHER},
                  "application/octet-stream": {
                      "extension": [".a", ".uu", ".psd", ".o", ".lha", ".lhx", ".com", ".dump",
                                    ".exe", ".lzh", ".lzx", ".saveme", ".zoo", ".arc", ".bin",
                                    ".arj"], "group": OTHER},
                  "application/oda": {"extension": [".oda"], "group": OTHER},
                  "application/pdf": {"extension": [".pdf"], "group": DOCUMENT},
                  "application/pkcs-12": {"extension": [".p12"], "group": OTHER},
                  "application/pkcs-crl": {"extension": [".crl"], "group": OTHER},
                  "application/pkcs10": {"extension": [".p10"], "group": OTHER},
                  "application/pkcs7-mime": {"extension": [".p7c", ".p7m"], "group": OTHER},
                  "application/pkcs7-signature": {"extension": [".p7s"], "group": OTHER},
                  "application/pkix-cert": {"extension": [".cer", ".crt"], "group": OTHER},
                  "application/pkix-crl": {"extension": [".crl"], "group": OTHER},
                  "application/plain": {"extension": [".text"], "group": OTHER},
                  "application/postscript": {"extension": [".ai", ".eps", ".ps"], "group": OTHER},
                  "application/powerpoint": {"extension": [".ppt"], "group": OTHER},
                  "application/pro_eng": {"extension": [".part", ".prt"], "group": OTHER},
                  "application/ringing-tones": {"extension": [".rng"], "group": OTHER},
                  "application/rtf": {"extension": [".rtf", ".rtx"], "group": OTHER},
                  "application/sdp": {"extension": [".sdp"], "group": OTHER},
                  "application/sea": {"extension": [".sea"], "group": OTHER},
                  "application/set": {"extension": [".set"], "group": OTHER},
                  "application/sla": {"extension": [".stl"], "group": OTHER},
                  "application/smil": {"extension": [".smi", ".smil"], "group": OTHER},
                  "application/solids": {"extension": [".sol"], "group": OTHER},
                  "application/sounder": {"extension": [".sdr"], "group": OTHER},
                  "application/step": {"extension": [".step", ".stp"], "group": OTHER},
                  "application/streamingmedia": {"extension": [".ssm"], "group": OTHER},
                  "application/toolbook": {"extension": [".tbk"], "group": OTHER},
                  "application/vda": {"extension": [".vda"], "group": OTHER},
                  "application/vnd.fdf": {"extension": [".fdf"], "group": OTHER},
                  "application/vnd.hp-hpgl": {"extension": [".hgl", ".hpg", ".hpgl"], "group": OTHER},
                  "application/vnd.hp-pcl": {"extension": [".pcl"], "group": OTHER},
                  "application/vnd.ms-excel": {"extension": [".xlw", ".xls", ".xlm", ".xll", ".xlb", ".xlc"],
                                               "group": OTHER},
                  "application/vnd.ms-pki.certstore": {"extension": [".sst"], "group": OTHER},
                  "application/vnd.ms-pki.pko": {"extension": [".pko"], "group": OTHER},
                  "application/vnd.ms-pki.seccat": {"extension": [".cat"], "group": OTHER},
                  "application/vnd.ms-pki.stl": {"extension": [".stl"], "group": OTHER},
                  "application/vnd.ms-powerpoint": {"extension": [".pot", ".ppa", ".pps", ".ppt", ".pwz"],
                                                    "group": OTHER},
                  "application/vnd.ms-project": {"extension": [".mpp"], "group": OTHER},
                  "application/vnd.nokia.configuration-message": {"extension": [".ncm"], "group": OTHER},
                  "application/vnd.nokia.ringing-tone": {"extension": [".rng"], "group": OTHER},
                  "application/vnd.rn-realmedia": {"extension": [".rm"], "group": OTHER},
                  "application/vnd.rn-realplayer": {"extension": [".rnx"], "group": OTHER},
                  "application/vnd.wap.wmlc": {"extension": [".wmlc"], "group": OTHER},
                  "application/vnd.wap.wmlscriptc": {"extension": [".wmlsc"], "group": OTHER},
                  "application/vnd.xara": {"extension": [".web"], "group": OTHER},
                  "application/vocaltec-media-desc": {"extension": [".vmd"], "group": OTHER},
                  "application/vocaltec-media-file": {"extension": [".vmf"], "group": OTHER},
                  "application/wordperfect": {"extension": [".wp5", ".wpd", ".wp6", ".wp"], "group": OTHER},
                  "application/wordperfect6.0": {"extension": [".wp5", ".w60"], "group": OTHER},
                  "application/wordperfect6.1": {"extension": [".w61"], "group": OTHER},
                  "application/x-123": {"extension": [".wk1"], "group": OTHER},
                  "application/x-aim": {"extension": [".aim"], "group": OTHER},
                  "application/x-authorware-bin": {"extension": [".aab"], "group": OTHER},
                  "application/x-authorware-map": {"extension": [".aam"], "group": OTHER},
                  "application/x-authorware-seg": {"extension": [".aas"], "group": OTHER},
                  "application/x-bcpio": {"extension": [".bcpio"], "group": OTHER},
                  "application/x-binary": {"extension": [".bin"], "group": OTHER},
                  "application/x-binhex40": {"extension": [".hqx"], "group": OTHER},
                  "application/x-bsh": {"extension": [".sh", ".shar", ".bsh"], "group": OTHER},
                  "application/x-bytecode.python": {"extension": [".pyc"], "group": OTHER},
                  "application/x-python-code": {"extension": [".pyc"], "group": OTHER},
                  "application/x-bzip": {"extension": [".bz"], "group": OTHER},
                  "application/x-bzip2": {"extension": [".boz", ".bz2"], "group": OTHER},
                  "application/x-cdf": {"extension": [".cdf"], "group": OTHER},
                  "application/x-cbr": {"extension": [".cbr"], "group": BOOK},
                  "application/x-cdlink": {"extension": [".vcd"], "group": OTHER},
                  "application/x-chat": {"extension": [".cha", ".chat"], "group": OTHER},
                  "application/x-cmu-raster": {"extension": [".ras"], "group": OTHER},
                  "application/x-cocoa": {"extension": [".cco"], "group": OTHER},
                  "application/x-compactpro": {"extension": [".cpt"], "group": OTHER},
                  "application/x-compress": {"extension": [".z"], "group": OTHER},
                  "application/x-compressed": {"extension": [".gz", ".tgz", ".zip", ".z"], "group": OTHER},
                  "application/x-conference": {"extension": [".nsc"], "group": OTHER},
                  "application/x-cpio": {"extension": [".cpio"], "group": OTHER},
                  "application/x-cpt": {"extension": [".cpt"], "group": OTHER},
                  "application/x-csh": {"extension": [".csh"], "group": OTHER},
                  "application/x-deepv": {"extension": [".deepv"], "group": OTHER},
                  "application/x-director": {"extension": [".dir", ".dcr", ".dxr"], "group": OTHER},
                  "application/x-dvi": {"extension": [".dvi"], "group": OTHER},
                  "application/x-elc": {"extension": [".elc"], "group": OTHER},
                  "application/x-envoy": {"extension": [".evy", ".env"], "group": OTHER},
                  "application/x-esrehber": {"extension": [".es"], "group": OTHER},
                  "application/epub+zip": {"extension": [".epub"], "group": BOOK},
                  "application/x-excel": {"extension": [".xlv", ".xlw", ".xlt", ".xls", ".xlm", ".xlk", ".xld", ".xll",
                                                        ".xla", ".xlb", ".xlc"], "group": OTHER},
                  "application/x-frame": {"extension": [".mif"], "group": OTHER},
                  "application/x-freelance": {"extension": [".pre"], "group": OTHER},
                  "application/x-gsp": {"extension": [".gsp"], "group": OTHER},
                  "application/x-gss": {"extension": [".gss"], "group": OTHER},
                  "application/x-gtar": {"extension": [".gtar"], "group": OTHER},
                  "application/x-gzip": {"extension": [".gz", ".gzip"], "group": OTHER},
                  "application/x-hdf": {"extension": [".hdf"], "group": OTHER},
                  "application/x-helpfile": {"extension": [".help", ".hlp"], "group": OTHER},
                  "application/x-httpd-imap": {"extension": [".imap"], "group": OTHER},
                  "application/x-ima": {"extension": [".ima"], "group": OTHER},
                  "application/x-internett-signup": {"extension": [".ins"], "group": OTHER},
                  "application/x-inventor": {"extension": [".iv"], "group": OTHER},
                  "application/x-ip2": {"extension": [".ip"], "group": OTHER},
                  "application/x-java-class": {"extension": [".class"], "group": OTHER},
                  "application/x-java-commerce": {"extension": [".jcm"], "group": OTHER},
                  "application/x-javascript": {"extension": [".js"], "group": OTHER},
                  "application/x-koan": {"extension": [".skt", ".skp", ".skm.skd"], "group": OTHER},
                  "application/x-ksh": {"extension": [".ksh"], "group": OTHER},
                  "application/x-latex": {"extension": [".latex", ".ltx"], "group": OTHER},
                  "application/x-lha": {"extension": [".lha"], "group": OTHER},
                  "application/x-lisp": {"extension": [".lsp"], "group": OTHER},
                  "application/x-livescreen": {"extension": [".ivy"], "group": OTHER},
                  "application/x-lotus": {"extension": [".wq1"], "group": OTHER},
                  "application/x-lotusscreencam": {"extension": [".scm"], "group": OTHER},
                  "application/x-lzh": {"extension": [".lzh"], "group": OTHER},
                  "application/x-lzx": {"extension": [".lzx"], "group": OTHER},
                  "application/x-mac-binhex40": {"extension": [".hqx"], "group": OTHER},
                  "application/x-macbinary": {"extension": [".bin"], "group": OTHER},
                  "application/x-magic-cap-package-1.0": {"extension": [".mc$"], "group": OTHER},
                  "application/x-mathcad": {"extension": [".mcd"], "group": OTHER},
                  "application/x-meme": {"extension": [".mm"], "group": OTHER},
                  "application/x-midi": {"extension": [".mid", ".midi"], "group": OTHER},
                  "application/x-mif": {"extension": [".mif"], "group": OTHER},
                  "application/x-mix-transfer": {"extension": [".nix"], "group": OTHER},
                  "application/x-mplayer2": {"extension": [".asx"], "group": OTHER},
                  "application/x-msexcel": {"extension": [".xla", ".xls", ".xlw"], "group": OTHER},
                  "application/x-mspowerpoint": {"extension": [".ppt"], "group": OTHER},
                  "application/x-navi-animation": {"extension": [".ani"], "group": OTHER},
                  "application/x-navidoc": {"extension": [".nvd"], "group": OTHER},
                  "application/x-navimap": {"extension": [".map"], "group": OTHER},
                  "application/x-navistyle": {"extension": [".stl"], "group": OTHER},
                  "application/x-netcdf": {"extension": [".cdf", ".nc"], "group": OTHER},
                  "application/x-newton-compatible-pkg": {"extension": [".pkg"], "group": OTHER},
                  "application/x-nokia-9000-communicator-add-on-software": {"extension": [".aos"], "group": OTHER},
                  "application/x-omc": {"extension": [".omc"], "group": OTHER},
                  "application/x-omcdatamaker": {"extension": [".omcd"], "group": OTHER},
                  "application/x-omcregerator": {"extension": [".omcr"], "group": OTHER},
                  "application/x-pagemaker": {"extension": [".pm4", ".pm5"], "group": OTHER},
                  "application/x-pcl": {"extension": [".pcl"], "group": OTHER},
                  "application/x-pixclscript": {"extension": [".plx"], "group": OTHER},
                  "application/x-pkcs10": {"extension": [".p10"], "group": OTHER},
                  "application/x-pkcs12": {"extension": [".p12"], "group": OTHER},
                  "application/x-pkcs7-certificates": {"extension": [".spc"], "group": OTHER},
                  "application/x-pkcs7-certreqresp": {"extension": [".p7r"], "group": OTHER},
                  "application/x-pkcs7-mime": {"extension": [".p7c", ".p7m"], "group": OTHER},
                  "application/x-pkcs7-signature": {"extension": [".p7a"], "group": OTHER},
                  "application/x-pointplus": {"extension": [".css"], "group": OTHER},
                  "application/x-portable-anymap": {"extension": [".pnm"], "group": OTHER},
                  "application/x-project": {"extension": [".mpc", ".mpt", ".mpv", ".mpx"], "group": OTHER},
                  "application/x-qpro": {"extension": [".wb1"], "group": OTHER},
                  "application/x-rtf": {"extension": [".rtf"], "group": OTHER},
                  "application/x-sdp": {"extension": [".sdp"], "group": OTHER},
                  "application/x-sea": {"extension": [".sea"], "group": OTHER},
                  "application/x-seelogo": {"extension": [".sl"], "group": OTHER},
                  "application/x-sh": {"extension": [".sh"], "group": OTHER},
                  "application/x-shar": {"extension": [".sh", ".shar"], "group": OTHER},
                  "application/x-shockwave-flash": {"extension": [".swf"], "group": OTHER},
                  "application/x-sit": {"extension": [".sit"], "group": OTHER},
                  "application/x-sprite": {"extension": [".spr", ".sprite"], "group": OTHER},
                  "application/x-stuffit": {"extension": [".sit"], "group": OTHER},
                  "application/x-sv4cpio": {"extension": [".sv4cpio"], "group": OTHER},
                  "application/x-sv4crc": {"extension": [".sv4crc"], "group": OTHER},
                  "application/x-tar": {"extension": [".tar"], "group": OTHER},
                  "application/x-tbook": {"extension": [".sbk", ".tbk"], "group": OTHER},
                  "application/x-tcl": {"extension": [".tcl"], "group": OTHER},
                  "application/x-tex": {"extension": [".tex"], "group": OTHER},
                  "application/x-texinfo": {"extension": [".texi", ".texinfo"], "group": OTHER},
                  "application/x-troff": {"extension": [".roff", ".t", ".tr"], "group": OTHER},
                  "application/x-troff-man": {"extension": [".man"], "group": OTHER},
                  "application/x-troff-me": {"extension": [".me"], "group": OTHER},
                  "application/x-troff-ms": {"extension": [".ms"], "group": OTHER},
                  "application/x-troff-msvideo": {"extension": [".avi"], "group": OTHER},
                  "application/x-ustar": {"extension": [".ustar"], "group": OTHER},
                  "application/x-visio": {"extension": [".vsd", ".vst", ".vsw"], "group": OTHER},
                  "application/x-vnd.audioexplosion.mzz": {"extension": [".mzz"], "group": OTHER},
                  "application/x-vnd.ls-xpix": {"extension": [".xpix"], "group": OTHER},
                  "application/x-vrml": {"extension": [".vrml"], "group": OTHER},
                  "application/x-wais-source": {"extension": [".src", ".wsrc"], "group": OTHER},
                  "application/x-winhelp": {"extension": [".hlp"], "group": OTHER},
                  "application/x-wintalk": {"extension": [".wtk"], "group": OTHER},
                  "application/x-world": {"extension": [".svr", ".wrl"], "group": OTHER},
                  "application/x-wpwin": {"extension": [".wpd"], "group": OTHER},
                  "application/x-wri": {"extension": [".wri"], "group": OTHER},
                  "application/x-x509-ca-cert": {"extension": [".crt", ".cer", ".der"], "group": OTHER},
                  "application/x-x509-user-cert": {"extension": [".crt"], "group": OTHER},
                  "application/x-zip-compressed": {"extension": [".zip"], "group": OTHER},
                  "application/xml": {"extension": [".xml"], "group": OTHER},
                  "application/zip": {"extension": [".zip"], "group": OTHER},
                  "audio/aiff": {"extension": [".aif", ".aifc", ".aiff"], "group": AUDIO},
                  "audio/basic": {"extension": [".au", ".snd"], "group": AUDIO},
                  "audio/it": {"extension": [".it"], "group": AUDIO},
                  "audio/make": {"extension": [".funk", ".my", ".pfunk"], "group": AUDIO},
                  "audio/make.my.funk": {"extension": [".pfunk"], "group": AUDIO},
                  "audio/mid": {"extension": [".rmi"], "group": AUDIO},
                  "audio/midi": {"extension": [".kar", ".midi", ".mid"], "group": AUDIO},
                  "audio/mod": {"extension": [".mod"], "group": AUDIO},
                  "audio/mpeg": {"extension": [".m2a", ".mp2", ".mpa", ".mpg", ".mpga"], "group": AUDIO},
                  "audio/mpeg3": {"extension": [".mp3"], "group": AUDIO},
                  "audio/nspaudio": {"extension": [".la", ".lma"], "group": AUDIO},
                  "audio/s3m": {"extension": [".s3m"], "group": AUDIO},
                  "audio/tsp-audio": {"extension": [".tsi"], "group": AUDIO},
                  "audio/tsplayer": {"extension": [".tsp"], "group": AUDIO},
                  "audio/vnd.qcelp": {"extension": [".qcp"], "group": AUDIO},
                  "audio/voc": {"extension": [".voc"], "group": AUDIO},
                  "audio/voxware": {"extension": [".vox"], "group": AUDIO},
                  "audio/wav": {"extension": [".wav"], "group": AUDIO},
                  "audio/x-adpcm": {"extension": [".snd"], "group": AUDIO},
                  "audio/x-aiff": {"extension": [".aif", ".aifc", ".aiff"], "group": AUDIO},
                  "audio/x-au": {"extension": [".au"], "group": AUDIO},
                  "audio/x-gsm": {"extension": [".gsd", ".gsm"], "group": AUDIO},
                  "audio/x-jam": {"extension": [".jam"], "group": AUDIO},
                  "audio/x-liveaudio": {"extension": [".lam"], "group": AUDIO},
                  "audio/x-mid": {"extension": [".mid", ".midi"], "group": AUDIO},
                  "audio/x-midi": {"extension": [".mid", ".midi"], "group": AUDIO},
                  "audio/x-mod": {"extension": [".mod"], "group": AUDIO},
                  "audio/x-mpeg": {"extension": [".mp2"], "group": AUDIO},
                  "audio/x-mpeg-3": {"extension": [".mp3"], "group": AUDIO},
                  "audio/x-mpequrl": {"extension": [".m3u"], "group": AUDIO},
                  "audio/x-nspaudio": {"extension": [".la", ".lma"], "group": AUDIO},
                  "audio/x-pn-realaudio": {"extension": [".ra", ".ram", ".rm", ".rmm", ".rmp"], "group": AUDIO},
                  "audio/x-pn-realaudio-plugin": {"extension": [".ra", ".rmp", ".rpm"], "group": AUDIO},
                  "audio/x-psid": {"extension": [".sid"], "group": AUDIO},
                  "audio/x-realaudio": {"extension": [".ra"], "group": AUDIO},
                  "audio/x-twinvq": {"extension": [".vqf"], "group": AUDIO},
                  "audio/x-twinvq-plugin": {"extension": [".vqe", ".vql"], "group": AUDIO},
                  "audio/x-vnd.audioexplosion.mjuicemediafile": {"extension": [".mjf"], "group": AUDIO},
                  "audio/x-voc": {"extension": [".voc"], "group": AUDIO},
                  "audio/x-wav": {"extension": [".wav"], "group": AUDIO},
                  "audio/xm": {"extension": [".xm"], "group": AUDIO},
                  "chemical/x-pdb": {"extension": [".pdb", ".xyz"], "group": OTHER},
                  "i-world/i-vrml": {"extension": [".ivr"], "group": OTHER},
                  "image/bmp": {"extension": [".bm", ".bmp"], "group": IMAGE},
                  "image/cmu-raster": {"extension": [".ras", ".rast"], "group": IMAGE},
                  "image/fif": {"extension": [".fif"], "group": IMAGE},
                  "image/florian": {"extension": [".flo", ".turbot"], "group": IMAGE},
                  "image/g3fax": {"extension": [".g3"], "group": IMAGE},
                  "image/gif": {"extension": [".gif"], "group": IMAGE},
                  "image/ief": {"extension": [".ief", ".iefs"], "group": IMAGE},
                  "image/jpeg": {"extension": [".jfif", ".jfif-tbnl", ".jpe", ".jpeg", "jpg"], "group": IMAGE},
                  "image/jutvision": {"extension": [".jut"], "group": IMAGE},
                  "image/naplps": {"extension": [".nap", ".naplps"], "group": IMAGE},
                  "image/pict": {"extension": [".pic", ".pict"], "group": IMAGE},
                  "image/pjpeg": {"extension": [".jfif", ".jpe", ".jpeg", ".jpg"], "group": IMAGE},
                  "image/png": {"extension": [".png", ".x-png"], "group": IMAGE},
                  "image/tiff": {"extension": [".tif", ".tiff"], "group": IMAGE},
                  "image/vasa": {"extension": [".mcf"], "group": IMAGE},
                  "image/vnd.dwg": {"extension": [".dxf", ".svf", ".dwg"], "group": IMAGE},
                  "image/vnd.fpx": {"extension": [".fpx"], "group": IMAGE},
                  "image/vnd.net-fpx": {"extension": [".fpx"], "group": IMAGE},
                  "image/vnd.rn-realflash": {"extension": [".rf"], "group": IMAGE},
                  "image/vnd.rn-realpix": {"extension": [".rp"], "group": IMAGE},
                  "image/vnd.wap.wbmp": {"extension": [".wbmp"], "group": IMAGE},
                  "image/vnd.xiff": {"extension": [".xif"], "group": IMAGE},
                  "image/x-cmu-raster": {"extension": [".ras"], "group": IMAGE},
                  "image/x-dwg": {"extension": [".svf", ".dwg", ".dxf"], "group": IMAGE},
                  "image/x-icon": {"extension": [".ico"], "group": IMAGE},
                  "image/x-jg": {"extension": [".art"], "group": IMAGE},
                  "image/x-jps": {"extension": [".jps"], "group": IMAGE},
                  "image/x-niff": {"extension": [".nif", ".niff"], "group": IMAGE},
                  "image/x-pcx": {"extension": [".pcx"], "group": IMAGE},
                  "image/x-pict": {"extension": [".pct"], "group": IMAGE},
                  "image/x-portable-anymap": {"extension": [".pnm"], "group": IMAGE},
                  "image/x-portable-bitmap": {"extension": [".pbm"], "group": IMAGE},
                  "image/x-portable-graymap": {"extension": [".pgm"], "group": IMAGE},
                  "image/x-portable-greymap": {"extension": [".pgm"], "group": IMAGE},
                  "image/x-portable-pixmap": {"extension": [".ppm"], "group": IMAGE},
                  "image/x-quicktime": {"extension": [".qif", ".qti", ".qtif"], "group": IMAGE},
                  "image/x-rgb": {"extension": [".rgb"], "group": IMAGE},
                  "image/x-tiff": {"extension": [".tif", ".tiff"], "group": IMAGE},
                  "image/x-windows-bmp": {"extension": [".bmp"], "group": IMAGE},
                  "image/x-xbitmap": {"extension": [".xbm"], "group": IMAGE},
                  "image/x-xbm": {"extension": [".xbm"], "group": IMAGE},
                  "image/x-xpixmap": {"extension": [".pm", ".xpm"], "group": IMAGE},
                  "image/x-xwd": {"extension": [".xwd"], "group": IMAGE},
                  "image/x-xwindowdump": {"extension": [".xwd"], "group": IMAGE},
                  "image/xbm": {"extension": [".xbm"], "group": OTHER},
                  "image/xpm": {"extension": [".xpm"], "group": IMAGE},
                  "message/rfc822": {"extension": [".mht", ".mhtml", ".mime"], "group": OTHER},
                  "model/iges": {"extension": [".iges", ".igs"], "group": OTHER},
                  "model/vnd.dwf": {"extension": [".dwf"], "group": OTHER},
                  "model/vrml": {"extension": [".vrml", ".wrl", ".wrz"], "group": OTHER},
                  "model/x-pov": {"extension": [".pov"], "group": OTHER},
                  "multipart/x-gzip": {"extension": [".gzip"], "group": OTHER},
                  "multipart/x-ustar": {"extension": [".ustar"], "group": OTHER},
                  "multipart/x-zip": {"extension": [".zip"], "group": OTHER},
                  "music/crescendo": {"extension": [".mid", ".midi"], "group": OTHER},
                  "music/x-karaoke": {"extension": [".kar"], "group": OTHER},
                  "paleovu/x-pv": {"extension": [".pvu"], "group": OTHER},
                  "text/asp": {"extension": [".asp"], "group": OTHER},
                  "text/css": {"extension": [".css"], "group": OTHER},
                  "text/ecmascript": {"extension": [".js"], "group": OTHER},
                  "text/html": {"extension": [".acgi", ".html", ".htm", ".htx", ".shtml"], "group": OTHER},
                  "text/javascript": {"extension": [".js"], "group": OTHER},
                  "text/mcf": {"extension": [".mcf"], "group": OTHER},
                  "text/pascal": {"extension": [".pas"], "group": OTHER},
                  "text/plain": {"extension": [".txt", ".text", ".sdml", ".pl", ".mar", ".m", ".log", ".lst", ".c",
                                               ".cc", ".com", ".conf", ".cxx", ".def", ".f", ".f90", ".for", ".g",
                                               ".h", ".hh", ".idc", ".jav", ".java", ".list", ".c++"], "group": OTHER},
                  "text/richtext": {"extension": [".rt", ".rtf", ".rtx"], "group": OTHER},
                  "text/scriplet": {"extension": [".wsc"], "group": OTHER},
                  "text/sgml": {"extension": [".sgm", ".sgml"], "group": OTHER},
                  "text/tab-separated-values": {"extension": [".tsv"], "group": OTHER},
                  "text/uri-list": {"extension": [".uni", ".unis", ".uri", ".uris"], "group": OTHER},
                  "text/vnd.abc": {"extension": [".abc"], "group": OTHER},
                  "text/vnd.fmi.flexstor": {"extension": [".flx"], "group": OTHER},
                  "text/vnd.rn-realtext": {"extension": [".rt"], "group": OTHER},
                  "text/vnd.wap.wml": {"extension": [".wml"], "group": OTHER},
                  "text/vnd.wap.wmlscript": {"extension": [".wmls"], "group": OTHER},
                  "text/webviewhtml": {"extension": [".htt"], "group": OTHER},
                  "text/x-asm": {"extension": [".asm", ".s"], "group": OTHER},
                  "text/x-audiosoft-intra": {"extension": [".aip"], "group": OTHER},
                  "text/x-c": {"extension": [".c", ".cc", ".cpp"], "group": OTHER},
                  "text/x-component": {"extension": [".htc"], "group": OTHER},
                  "text/x-fortran": {"extension": [".for", ".f", ".f77", ".f90"], "group": OTHER},
                  "text/x-h": {"extension": [".h", ".hh"], "group": OTHER},
                  "text/x-java-source": {"extension": [".jav", ".java"], "group": OTHER},
                  "text/x-la-asf": {"extension": [".lsx"], "group": OTHER},
                  "text/x-m": {"extension": [".m"], "group": OTHER},
                  "text/x-pascal": {"extension": [".p"], "group": OTHER},
                  "text/x-python": {"extension": ['.py'], "group": OTHER},
                  "text/x-script": {"extension": [".hlb"], "group": OTHER},
                  "text/x-script.csh": {"extension": [".csh"], "group": OTHER},
                  "text/x-script.elisp": {"extension": [".el"], "group": OTHER},
                  "text/x-script.guile": {"extension": [".scm"], "group": OTHER},
                  "text/x-script.ksh": {"extension": [".ksh"], "group": OTHER},
                  "text/x-script.lisp": {"extension": [".lsp"], "group": OTHER},
                  "text/x-script.perl": {"extension": [".pl"], "group": OTHER},
                  "text/x-script.perl-module": {"extension": [".pm"], "group": OTHER},
                  "text/x-script.phyton": {"extension": [".py"], "group": OTHER},
                  "text/x-script.rexx": {"extension": [".rexx"], "group": OTHER},
                  "text/x-script.scheme": {"extension": [".scm"], "group": OTHER},
                  "text/x-script.sh": {"extension": [".sh"], "group": OTHER},
                  "text/x-script.tcl": {"extension": [".tcl"], "group": OTHER},
                  "text/x-script.tcsh": {"extension": [".tcsh"], "group": OTHER},
                  "text/x-script.zsh": {"extension": [".zsh"], "group": OTHER},
                  "text/x-server-parsed-html": {"extension": [".shtml", ".ssi"], "group": OTHER},
                  "text/x-setext": {"extension": [".etx"], "group": OTHER},
                  "text/x-sgml": {"extension": [".sgm", ".sgml"], "group": OTHER},
                  "text/x-speech": {"extension": [".spc", ".talk"], "group": OTHER},
                  "text/x-uil": {"extension": [".uil"], "group": OTHER},
                  "text/x-uuencode": {"extension": [".uu", ".uue"], "group": OTHER},
                  "text/x-vcalendar": {"extension": [".vcs"], "group": OTHER},
                  "text/xml": {"extension": [".xml"], "group": OTHER},
                  "video/animaflex": {"extension": [".afl"], "group": VIDEO},
                  "video/avi": {"extension": [".avi"], "group": VIDEO},
                  "video/avs-video": {"extension": [".avs"], "group": VIDEO},
                  "video/dl": {"extension": [".dl"], "group": VIDEO},
                  "video/fli": {"extension": [".fli"], "group": OTHER},
                  "video/gl": {"extension": [".gl"], "group": VIDEO},
                  "video/mpeg": {"extension": [".m1v", ".m2v", ".mp2", ".mp3", ".mpa", ".mpe", ".mpeg", ".mpg"],
                                 "group": OTHER}, "video/msvideo": {"extension": [".avi"], "group": VIDEO},
                  "video/quicktime": {"extension": [".moov", ".mov", ".qt"], "group": VIDEO},
                  "video/vdo": {"extension": [".vdo"], "group": VIDEO},
                  "video/vivo": {"extension": [".viv", ".vivo"], "group": VIDEO},
                  "video/vnd.rn-realvideo": {"extension": [".rv"], "group": VIDEO},
                  "video/vnd.vivo": {"extension": [".viv", ".vivo"], "group": VIDEO},
                  "video/vosaic": {"extension": [".vos"], "group": VIDEO},
                  "video/x-amt-demorun": {"extension": [".xdr"], "group": VIDEO},
                  "video/x-amt-showrun": {"extension": [".xsr"], "group": VIDEO},
                  "video/x-atomic3d-feature": {"extension": [".fmf"], "group": VIDEO},
                  "video/x-dl": {"extension": [".dl"], "group": VIDEO},
                  "video/x-dv": {"extension": [".dv", ".dif"], "group": VIDEO},
                  "video/x-fli": {"extension": [".fli"], "group": VIDEO},
                  "video/x-gl": {"extension": [".gl"], "group": VIDEO},
                  "video/x-isvideo": {"extension": [".isu"], "group": VIDEO},
                  "video/x-motion-jpeg": {"extension": [".mjpg"], "group": VIDEO},
                  "video/x-mpeg": {"extension": [".mp2", ".mp3"], "group": VIDEO},
                  "video/x-mpeq2a": {"extension": [".mp2"], "group": VIDEO},
                  "video/x-ms-asf": {"extension": [".asf", ".asx"], "group": VIDEO},
                  "video/x-ms-asf-plugin": {"extension": [".asx"], "group": VIDEO},
                  "video/x-msvideo": {"extension": [".avi"], "group": VIDEO},
                  "video/x-qtc": {"extension": [".qtc"], "group": VIDEO},
                  "video/x-scm": {"extension": [".scm"], "group": VIDEO},
                  "video/x-sgi-movie": {"extension": [".movie", ".mv"], "group": VIDEO},
                  "windows/metafile": {"extension": [".wmf"], "group": OTHER},
                  "www/mime": {"extension": [".mime"], "group": OTHER},
                  "x-conference/x-cooltalk": {"extension": [".ice"], "group": OTHER},
                  "x-music/x-midi": {"extension": [".mid", ".midi"], "group": OTHER},
                  "x-world/x-3dmf": {"extension": [".3dm", ".qd3d", ".qd3", ".3dmf"], "group": OTHER},
                  "x-world/x-svr": {"extension": [".svr"], "group": OTHER},
                  "x-world/x-vrml": {"extension": [".vrml", ".wrl", ".wrz"], "group": OTHER},
                  "x-world/x-vrt": {"extension": [".vrt"], "group": OTHER},
                  "xgl/drawing": {"extension": [".xgz"], "group": OTHER},
                  "xgl/movie": {"extension": [".xmz"], "group": OTHER}}
